profil_list = [
    "étudiant","étudiante","Ingénieure en informatique", "Développeur logiciel",
    "Ingénieur logiciel",
    "Analyste de données",
    "Architecte système",
    "Administrateur réseau",
    "Administrateur de bases de données",
    "Ingénieur DevOps",
    "Ingénieur en sécurité informatique",
    "Analyste en intelligence artificielle",
    "Spécialiste en cybersécurité",
    "Consultant en technologies de l'information","Consultant en réseaux ",
    "Chef de projet informatique",
    "Expert en cloud computing",
    "Administrateur système",
    "Ingénieur en apprentissage automatique",
    "Architecte de solutions",
    "Analyste en assurance qualité",
    "Expert en bases de données",
    "Développeur web",
    "Développeur d'applications mobiles",
    "Analyste en business intelligence","ingénieur en génie civil",
    "Ingénieur DevOps",
    "Développeur full-stack",
    "Data scientist",
    "Analyste en sécurité des systèmes",
    "Expert en apprentissage automatique",
    "Architecte de données",
    "Ingénieur cloud",
    "Spécialiste en automatisation des processus",
    "Développeur front-end",
    "Ingénieur en réalité virtuelle",
    "Administrateur de systèmes Linux",
    "Consultant en blockchain",
    "Analyste en big data",
    "Ingénieur en intelligence artificielle",
    "Spécialiste en gestion de projet agile",
    "Développeur d'applications mobiles",
    "Architecte logiciel",
    "Ingénieur réseau",
    "Analyste en sécurité des données",
    "Expert en analyse de données",
    "Consultant SAP",
    "Architecte technique SAP",
    "Analyste fonctionnel SAP",
    "Développeur ABAP",
    "Spécialiste SAP HANA",
    "Expert en intégration SAP",
    "Administrateur système SAP",
    "Chef de projet SAP",
    "Consultant SAP FI/CO",
    "Analyste de données SAP",
    "Ingénieur de support SAP",
    "Développeur SAP BW/BI",
    "Spécialiste SAP SD",
    "Consultant SAP MM",
    "Architecte de paysage SAP",
    "Expert en gestion des autorisations SAP",
    "Consultant SAP CRM",
    "Analyste de la chaîne logistique SAP",
    "Développeur SAP Fiori",
    "Spécialiste SAP PM"
]
