technical_skills_list = [ 'autocad', 'arche','pack office', 'global mapper', 'robot structural analysis',
    'spring boot', 'Natural Language Processing (NLP)',
'sap crm', 'quikview', 'Communication Skills','big data analytics', 'Quality Assurance', 'Mobile App Design',
'Java (Android)', 'sap', 'cloud computing', 'bi', 'c++','Data Science', 'artificial intelligence', 'Networking', 'sql',
'mobile app design', 'Push Notifications', 'Big Data Analytics','apache hadoop', 'react native', 'Data Warehousing', 'security', 'organisé'
'machine learning', 'SAP BW/BI', 'React Native', 'sap', 'it support','NoSQL', 'Quikview', 'r', 'aws', 'agile methodology', 'natural language processing (nlp)', 
'Flutter', 'testing', 'sap mm', 'AWS', 'Data Government and Testing', 'Cloud Computing', 'data mining', 'SAP S/4HANA', 'troubleshooting', 'docker', 'restful apis', 'scripting', 
'Google Cloud', 'data governance and testing', 'SAP MM', 'SAP CRM', 'Python', 'Teamwork', 'java', 'marketing', 'Predictive Modeling', 'mobile ui/ux', 'business intelligence',
'database management', 'C++', 'push notifications', 'computer vision', 'data pipeline','google cloud', 'Data Integration', 'version control', 'mobile', 'advanced analytics', 'IT Support', 'etl (extract, transform, load)', 'front-end frameworks', 'sap sd','Mobile UI/UX', 'data integration', 'data engineerQuikview', 'statistical analysis', 
'Linux/Unix', 'Troubleshooting', 'firebase', 'SAP HANA', 'systems integration', 'python', 'amplitude', 'agiles', 'sap bw/bi', 'apache spark', 'ETL (Extract, Transform, Load)', 
'Kotlin (Android)', 'problem solving', 'Google Analytics', 'java (android)', 'Data Pipeline','sap fiori', 'Data Mining', 'data studio', 'SQL', 'project management', 'SAP', 'Tableau', 
'Deep Learning', 'Agile Methodology', 'Front-end Frameworks', 'sap abap', 'sap fico', 'Apache Spark', 'networking', 'Scripting', 'Testing', 'devops', 'Artificial Intelligence','SAP ABAP', 'objective-c (ios)', 'system administration', 'Objective-C (iOS)', 
'Software Development Life Cycle (SDLC)', 'Machine Learning', 'Azure', 'R', 'informatique','Database Management', 'Business Intelligence', 'web', 'data warehousing', 'software development life cycle (sdlc)', 'Advanced Analytics', 'data visualization',
'java','angular', 'Apache Hadoop', 'data engineer','sql', 'Amplitude', 'System Administration', 'Git','Data Visualization', 'Data Studio', 'flutter', 'quality assurance', 'linux/unix', 'SAP ERP', 'swift (ios)', 
'sap erp', 'virtualization', 'Project Management', 'communication skills', 'deep learning', 'Technical Design',
'back-end frameworks', 'Systems Integration', 'SAP SD', 'google analytics', 'SAP Fiori', 'Statistical Analysis',
'sap hana', 'Virtualization', 'Problem Solving', 'data science', 'RESTful APIs', 'Security', 'kotlin (android)', 
'predictive modeling', 'Artificiel Intelligence', 'nosql', 'Version Control', 'Data Governance and Testing', 
'SAP FICO', 'php', 'git', 'technical design', 'Back-end Frameworks', 'azure', 'teamwork', 'tableau', 'Firebase','Swift (iOS)','la modélisation de données','analyse des données',' désireux','dynamique','rapide','english','anglais',
'français',' rigoureux','autonome','data analyst','SAP ERP','Oracle','MS SQL Server','SAP HANA','SAP ASE (Adaptive Server Enterprise)','SAP MaxDB','SAP SD (Sales and Distribution)',
'SAP MM (Materials Management)','SAP FI (Financial Accounting)','SAP ABAP (Advanced Business Application Programming)','SAP HR (Human Resources)','SAP FI/CO (Financial Accounting and Controlling)','SAP S/4HANA',
'SAP GIP (Gestion Intégrée des Processus)','SAP FI/CO Finance et Achats','Pack Office 365','Windows 10-11','Windows Server','VMware','LSMW (Legacy System Migration Workbench)',
'Interfaces','EDI (Electronic Data Interchange)','Management de projet','Rigoureux(se)','Force de proposition','Projet ERP',
'SAP FI-CO (Finance et Contrôle de Gestion)','SAP MM-SD (Materials Management et Sales and Distribution)','Collaboratif(ve)',
'Entrepreneur(e)','Anticonformiste','Esprit de famille','SAP S/4HANA','indsutrie','Curieux(se)','Comptabilité','Contrôle de gestion','Ressources humaines (RH) SAP']
